server:
  port: 9001
spring:
  application:
    name: albdemo02
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.16.250.152:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
  # redis
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password:
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 500
#        min-idle: 0
#    lettuce:
#      shutdown-timeout: 0
